apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2 
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: fathalla22/final:${BUILD_NUMBER}
        ports:
        - containerPort: 80

